name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 isort black mypy pytest

    - name: Run flake8
      run: flake8 .

    - name: Run isort
      run: isort . --check-only --diff

    - name: Run black
      run: black . --check --diff

    - name: Run mypy
      run: mypy .

    - name: Run tests
      run: pytest